<?php

namespace App\Helper;

class SchemaAddonImportHelper
{
    public static function getHeaderMap()
    {
        return [
            'ProductID' => 'product_id',
            'Schema ID' => 'schema_id',
            'Product Code' => 'product_code',
            'Product Class' => 'product_class',
            'Description' => 'description',
            'RETROFIT' => 'retrofit',
            'NAILON' => 'nailon',
            'BLOCK' => 'block',
            'CLR' => 'clr',
            'LE3' => 'le3',
            'LE3/CLR' => 'le3_clr',
            'CLR/CLR' => 'clr_clr',
            'LE3/LAMI' => 'le3_lam',
            'LE3/CLR/LE3' => 'le3_clr_le3',
            'CLR/TEMP' => 'clr_temp',
            '1LE3 + 1CLR TEMP' => 'onele3_1clrtemp',
            '2LE3 + 1CLR TEMP' => 'twole3_1clrtemp',
            'LAM EMP' => 'lam_temp',
            'CLT/CLT' => 'clt_clt',
            'LET/LET/LET' => 'let_let_let',
            'LE3/LAM/LE3' => 'le3_lam_le3',
            'LE3/LAMI/LE3' => 'le3_lam_le3',
            'LET/CLT/LET' => 'let_clt_let',
            'LET/LAM/LET' => 'let_lam_let',
            'LET/LAMI/LET' => 'let_lam_let',
            'LET/CLT' => 'let_clt',
            'OBS' => 'obs',
            'GERY' => 'gery',
            'RAIN' => 'rain',
            'TEMP' => 'temp',
            'CLR/LAM' => 'clr_lam',
            'COROR_MULTI' => 'color_multi',
            'BASE_MULIT' => 'base_multi',
            'FEAT1' => 'feat1',
            'FEAT2' => 'feat2',
            'FEAT3' => 'feat3',
            'STA GRD' => 'sta_grd',
            'TPI' => 'tpi',
            'TPO' => 'tpo',
            'Acid Etch' => 'acid_etch',
            'ACID EDGE' => 'acid_edge',
            'SOLAR COOL' => 'solar_cool',
            'SOLAR COOL_G' => 'solar_cool_g',
            'SALES_FACTOR' => 'sales_factor',
            'FACTOR' => 'sales_factor',
            'TCost' => 'total_cost',
            'COST/FT' => 'cost_ft',
            'COST/PC' => 'cost_pc',
            'COST' => 'cost',
            'COST1' => 'cost',
            'Cost' => 'cost',
            'MARK_UP' => 'mark_up',
            'RATE' => 'rate',
            'MCOST' => 'm_cost',
            'CALCULATED COST' => 'calculated_cost',
            'Cost per Inch' => 'cost_inch',
            'Unit per Box' => 'unit_box',
            'Price per Box' => 'price_box',
            'Price per Piece' => 'price_piece',
            'Box Weight' => 'box_weight',
            'Ft per Box' => 'ft_box',
            'In per Box' => 'inch_box',
            'Price per Inc' => 'price_inch',
            'VENT' => 'vent',
            'XFIX' => 'xfix',
            'FIX' => 'fix',
            'GRID' => 'grid',
            'LAM FOR IM AND GX' => 'lam_im_gx',
            'TWO PANEL FRAME' => 'two_panel_frame',
            'THREE PANEL FRAME' => 'three_panel_frame',
            'FOUR PANEL FRAME' => 'four_panel_frame',
            'PANEL' => 'panel',
            'PER SQ FT' => 'price_sq_ft',
            'STF' => 'stf',
            'LABRO STA' => 'labor_sta',
            'LABRO PER FIELD' => 'labor_field',
            'PROFIT' => 'profit',
            'Purchase_Price' => 'purchase_price',
            'Markup_Percentage' => 'markup_percentage',
            'Purchase by PC' => 'purchase_by_piece',
            'Purchase by BND(99)' => 'purchase_by_bnd_99',
            'Purchase by BND(54)' => 'purchase_by_bnd_54',
            'Purchase by BND(70)' => 'purchase_by_bnd_70',
            'Purchase by BND(63)' => 'purchase_by_bnd_63',
            'Purchase by BND(77)' => 'purchase_by_bnd_77',
            'Purchase by BND(49)' => 'purchase_by_bnd_49',
            'Purchase by BND(42)' => 'purchase_by_bnd_42',
            'Purchase by BND(396)' => 'purchase_by_bnd_396',
            'Purchase by BND(510)' => 'purchase_by_bnd_510',
            'Purchase by BND(341)' => 'purchase_by_bnd_341',
            'Purchase by BND(81)' => 'purchase_by_bnd_81',
            'Purchase by BND(72)' => 'purchase_by_bnd_72',
            'Purchase by BND(90)' => 'purchase_by_bnd_90',
        ];
    }
}
